name: Cache and Audit

on:
  push:
    branches: [main]

jobs:
  cache-and-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm packages
        run: npm install
      - name: Commit package-lock.json if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package-lock.json
          git diff --cached --quiet || git commit -m "Add package-lock.json for CI"
          git push
